os:
  - linux

language: go

sudo: false

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

go:
  - 1.7

install:
  - make deps

script:
  - make test

cache:
    directories:
        - $GOPATH/src/gx
